version: 2.1

parameters:
  app_name:
    type: string
    default: "$name;format="word-space,hyphenate"$"

orbs:
  aws-cli: circleci/aws-cli@3.0
  helm: circleci/helm@1.2.0

jobs:
  test:
    docker:
      - image: circleci/elixir:1.12.3
      $if(include_database.truthy)$
      - image: circleci/postgres:10.6
        environment:
          POSTGRES_USER: postgres
      $endif$

    working_directory: ~/$name$
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache

      - run:
          name: Install hex / rebar / dependencies
          command: |
            mix local.hex --force
            mix local.rebar --force
            mix hex.organization auth shore_gmbh --key \${HEXPM_API_KEY}
            mix deps.get
            mix deps.compile
            mix compile
            MIX_ENV=test mix compile

      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: ["deps"]
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: ["deps"]
      - save_cache:
          key: v1-mix-cache
          paths: ["deps"]
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths:
            - _build
            - ~/.mix
      - save_cache:
          key: v1-build-cache
          paths:
            - _build
            - ~/.mix

      - run:
          name: Run format checker
          command: mix format --check-formatted

      - run:
          name: Run credo
          command: mix credo --config-file .credo.exs --strict

      - run:
          name: Run tests
          $if(include_database.truthy)$
          environment:  
              DATABASE_URL: "postgres://postgres@localhost:5432/$name$_test"
          $endif$
          command: mix test

  deploy:
    parameters:
      env:
        type: string
      iam_role:
        type: string
      
    machine:
      image: ubuntu-2004:202201-02

    working_directory: ~/$name$

    steps:
      - checkout
      - aws-cli/setup
      - helm/install-helm-client:
          version: v3.7.0

      - run:
          command: |
             aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin \${AWS_ECR_ACCOUNT_URL}
             aws ecr describe-repositories --repository-names << pipeline.parameters.app_name >> || aws ecr create-repository --repository-name << pipeline.parameters.app_name >>
             docker build --build-arg HEXPM_API_KEY=\${HEXPM_API_KEY} . -t "<< pipeline.parameters.app_name >>:\${CIRCLE_BRANCH}-\${CIRCLE_SHA1}"
             docker tag "<< pipeline.parameters.app_name >>:\${CIRCLE_BRANCH}-\${CIRCLE_SHA1}" "\${AWS_ECR_ACCOUNT_URL}/<< pipeline.parameters.app_name >>:\${CIRCLE_BRANCH}-\${CIRCLE_SHA1}"
             docker push "\${AWS_ECR_ACCOUNT_URL}/<< pipeline.parameters.app_name >>:\${CIRCLE_BRANCH}-\${CIRCLE_SHA1}"
          name: Build and push docker image to ECR
      - run:
          command: |
              aws eks --region eu-central-1 update-kubeconfig --name << parameters.env >> --role arn:aws:iam::448433501390:role/<< parameters.iam_role >> --alias << parameters.env >>
              cd helm/ && helm upgrade -f values_<< parameters.env >>.yaml << pipeline.parameters.app_name >> . --install --namespace shore --set image.tag="\${CIRCLE_BRANCH}-\${CIRCLE_SHA1}"
          name: Deploy

workflows:
  version: 2
  test_build_and_deploy:
    jobs:
      - test:
          context:
            - hex-auth
          name: Test
      - confirm_staging:
          type: approval
          requires:
            - Test
          filters:
            branches:
              ignore: master
      - deploy:
          env: "staging"
          iam_role: staging-cluster-admin-users
          context:
            - aws
            - hex-auth
          name: Deploy to staging
          requires:
            - confirm_staging
          filters:
            branches:
              ignore: master
      - deploy:
          env: "prod"
          iam_role: prod-cluster-admin-users
          context:
            - aws
            - hex-auth
          name: Auto deploy to production
          requires:
            - Test
          filters:
            branches:
              only: master
