version: 2.1

parameters:
  app_name:
    type: string
    default: "elixir-template"

jobs:
  test:
    docker:
      - image: circleci/elixir:1.12.3

    working_directory: ~/elixir_template
    steps:
      - checkout

      - run:
          name: Install Giter8
          command: |
            curl https://repo1.maven.org/maven2/org/foundweekends/giter8/giter8-bootstrap_2.12/0.13.1/giter8-bootstrap_2.12-0.13.1.sh > /usr/local/bin/g8
            chmod +x usr/local/bin/g8
            g8 --help

      - run:
          name: Create application
          command: |
            cd ..
            g8 file://./elixir-template.g8 --name=my_app --include_database=no

workflows:
  version: 2
  test:
    jobs:
      - test:
          context:
            - hex-auth
          name: Test
