apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "$name;format="word-space,hyphenate"$.fullname" . }}
  labels:
    {{- include "$name;format="word-space,hyphenate"$.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "$name;format="word-space,hyphenate"$.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.rollingUpdate.maxSurge }}
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailable }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "$name;format="word-space,hyphenate"$.fullname" . }}
        {{- include "$name;format="word-space,hyphenate"$.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "$name;format="word-space,hyphenate"$.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.application.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.application.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.application.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.application.readinessProbe | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: {{ .Values.application.resources.limits.cpu }}
              memory: {{ .Values.application.resources.limits.memory }}
            requests:
              cpu: {{ .Values.application.resources.requests.cpu }}
              memory: {{ .Values.application.resources.requests.memory }}
          env:
            - name: DOGSTATSD_HOST_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: DD_SERVICE
              value: {{ include "$name;format="word-space,hyphenate"$.fullname" . }}
            - name: DD_VERSION
              value: {{ .Values.image.tag }}
          {{- range \$key, \$val := .Values.application.envs }}
            - name: {{ \$key }}
              value: {{ \$val | quote }}
          {{- end }}
          {{- range \$key, \$val := .Values.application.secrets }}
            - name: {{ \$key }}
              valueFrom:
                secretKeyRef:
                  name: $name;format="word-space,hyphenate"$
                  key: {{ \$val | quote }}
          {{- end }}
          {{- range \$key, \$val := .Values.application.globalSecrets }}
            - name: {{ \$key }}
              valueFrom:
                secretKeyRef:
                  name: global-secrets
                  key: {{ \$val | quote }}
          {{- end }}


      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
