{{- if .Values.ingress.enabled -}}

{{- \$serviceName := include "$name;format="word-space,hyphenate"$.fullname" . -}}
{{- \$servicePort := .Values.service.externalPort -}}
{{- \$path := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ \$serviceName }}-internal
  labels:
    {{- include "$name;format="word-space,hyphenate"$.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range \$host := .Values.ingress.hosts }}
    - host: {{ \$host }}
      http:
        paths:
        - path: {{ \$path }}
          backend:
            serviceName: {{ \$serviceName }}
            servicePort: {{ \$servicePort }}
    {{- end -}}
{{- end -}}
