apiVersion: v1
kind: Service
metadata:
  name: {{ include "dory.fullname" . }}
  labels:
    {{- include "dory.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ include "dory.fullname" . }}
