apiVersion: v1
kind: Service
metadata:
  name: {{ include "$name;format="word-space,hyphenate"$.fullname" . }}
  labels:
    {{- include "$name;format="word-space,hyphenate"$.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ include "$name;format="word-space,hyphenate"$.fullname" . }}
