version: '3'

services:
  $name$-dev-db:
    image: postgres:12.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: $name$_dev
    restart: always
    volumes:
      - $name$-dev-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  $name$-dev-db-data:

networks:
  host:
