version: '3'

services:
  app:
    build:
      context: ..
      args:
        MIX_ENV: prod
        HEXPM_API_KEY: test_test
    ports:
      - "127.0.0.1:4000:4000"
    environment:
      SHORE_API_BASE_URI: https://staging.shore.com
      SECRET_KEY_BASE: asdasdasdhajsdhjasdhjasdhjasdhaj
      $if(include_database.truthy)$
      DATABASE_URL: postgres://postgres:$name$@$name$-db:5432/postgres
      $endif$
      RABBITMQ_URL: amqp://$name$-rabbitmq
      SHORE_TOKEN_SECRET: asdasdasdasdasdasdds
    networks:
      - host
$if(include_database.truthy)$
    depends_on:
      - $name$-db

  $name$-db:
    image: postgres:12.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $name$
      POSTGRES_DB: $name$
    restart: always
    volumes:
      - $name$-db-data:/var/lib/postgresql/data
    networks:
      - host

volumes:
  $name$-db-data:
$endif$

networks:
  host:
