replicaCount: 1

image:
  repository: 448433501390.dkr.ecr.eu-central-1.amazonaws.com/$name;format="word-space,hyphenate"$
  pullPolicy: Always

nameOverride: "$name;format="word-space,hyphenate"$"   
fullnameOverride: "$name;format="word-space,hyphenate"$"

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0

serviceAccount:
  create: true
  annotations: {}
  name: "$name;format="word-space,hyphenate"$"

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext: {}

vpnService:
  enabled: false

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 4000

ingress:
  enabled: false

application:
  envs:
    DD_ENV: production
    APP_ENVIRONMENT: prod
    PORT: 4000
    SHORE_API_BASE_URI: http://api-internal
  secrets:
    $if(include_database.truthy)$
    DATABASE_URL: databaseUrl
    $endif$
    SECRET_KEY_BASE: secretKeyBase
    SENTRY_URL: sentryUrl
  globalSecrets:
    SHORE_TOKEN_SECRET: SHORE_TOKEN_SECRET
  readinessProbe:
    httpGet:
      path: /health
      port: 4000
    initialDelaySeconds: 60
    periodSeconds: 3
    timeoutSeconds: 10
  livenessProbe:
    httpGet:
      path: /health
      port: 4000
    initialDelaySeconds: 60
    periodSeconds: 3
    timeoutSeconds: 10
  resources:
    limits:
      cpu: 300m
      memory: 1Gi
    requests:
      cpu: 300m
      memory: 1Gi
  $if(include_database.truthy)$
  pre_upgrade_job:
    cmd: /home/elixir/app/bin/$name$ eval "$name$.ReleaseTasks.migrate()"
  $endif$

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
